# NumPy Pair Problem

For today's pair, we will use NumPy to complete the following tasks consecutively.

In [1]:
import numpy as np

# Set random seed so that results are reproducible 
np.random.seed(0)

### 1. Generate three separate 1-dimensional arrays of 10,000 elements each.
* Array 1 should contain numbers randomly drawn from the uniform distribution between 1 and 100
* Array 2 should contain numbers randomly drawn from the normal distribution, with a mean of 0 and a standard deviation of 1
* Array 3 should contain numbers randomly drawn from the binomial distribution, where n=10 and p=0.5

In [2]:
array1 = np.random.uniform(1,100,10000)
array1

array([55.33253689, 71.80374727, 60.67357423, ..., 76.08452255,
        3.35495532, 81.54393292])

In [5]:
array2 = np.random.normal(0, 1, 10000)
array2

array([ 0.0801362 , -1.4279162 , -0.16734997, ..., -0.98560151,
       -2.37661231, -0.34607402])

In [4]:
array3 = np.random.binomial(10 , 0.5 , 10000 )
array3

array([4, 5, 5, ..., 5, 4, 4])

### 2. For each array, randomly sample 1,000 rows without replacement. (hint: `np.random.choice()`)


In [6]:
array4 = np.random.choice(array1, 1000 , replace = False)
array4

array([82.8592987 , 66.66917494, 30.29903353, 89.83145995,  7.5744664 ,
       85.40963821, 94.55765092, 80.43800043, 24.76200706,  5.09739331,
       95.41691201, 31.65977028, 10.10117684, 98.24252995, 48.05715344,
       42.27646126, 12.65835192, 96.26547991, 43.65013594, 94.02480518,
        2.67029566, 67.01211138,  4.34563742, 23.25295551, 17.33181127,
       98.07743315, 69.56062742, 87.48810326, 98.28629453, 78.65691249,
       53.69253249, 18.71217837, 11.54325638, 64.20062047, 13.16294333,
       52.36467973, 10.00166705, 15.77226436, 46.76248056,  4.29623321,
       72.16705867, 12.90145005, 40.88793603, 25.70112418, 87.51612497,
       42.73348839, 51.27465074, 63.46589788, 67.42514045, 25.6343134 ,
        2.61401675, 26.03068083, 73.7790897 ,  9.49390648, 54.17690149,
       69.94781081, 40.97548133, 35.29304913, 47.59169679, 34.29871487,
       11.29422723, 48.23163918, 71.96910844, 24.64416516, 96.50387546,
       59.45172603,  5.42232867, 52.29683157, 70.71070522, 80.62

In [7]:
array5 = np.random.choice(array2, 1000 , replace = False)
array5

array([ 3.70541188e-01,  2.01886002e+00,  1.40791876e+00,  9.87073614e-02,
       -1.97446401e+00, -8.75782101e-01,  1.20346232e+00,  8.29031736e-01,
       -1.02296737e+00, -5.17217583e-01,  9.03754770e-01, -2.68170273e+00,
       -1.31548881e+00,  6.84189239e-01,  1.75220833e+00,  1.37447141e+00,
       -1.05858860e-01,  3.55621426e-01,  8.52719604e-01, -8.63538932e-02,
       -2.64829009e-01,  2.96754495e-01, -5.93237361e-01, -7.01819950e-01,
        2.53821932e+00, -1.46773035e+00,  7.72825896e-01, -6.07268264e-01,
        1.22477008e+00, -1.79591059e+00,  1.51956488e-01,  4.94906233e-01,
       -4.53227443e-01,  4.61774261e-01,  3.60131403e-01,  1.58549165e+00,
       -2.01485946e-01,  2.30039088e-02, -6.46621509e-01, -3.06263969e-01,
       -3.18917777e-02,  2.32487775e+00, -4.26673386e-01, -2.15256657e-01,
       -9.58160738e-01, -2.41348276e+00,  3.09279186e+00,  1.45142268e-01,
       -1.38170395e+00, -9.83709720e-02, -5.63772549e-01,  1.07230308e-02,
       -2.41562846e+00,  

In [8]:
array6 = np.random.choice(array3, 1000 , replace = False)
array6

array([ 4,  6,  5,  4,  5,  8,  6,  6,  6,  6,  5,  5,  6,  4,  8,  4,  7,
        5,  7,  4,  7,  8,  4,  8,  6,  1,  6,  6,  5,  7,  3,  6,  5,  5,
        4,  5,  5,  6,  7,  7,  5,  6,  7,  7,  7,  6,  4,  3,  5,  5,  6,
        6,  5,  6,  5,  6,  7,  7,  2,  6,  5,  1,  5,  6,  4,  6,  7,  5,
        6,  6,  9,  4,  3,  5,  6,  3,  3,  5,  6,  8,  5,  5,  7,  5,  4,
        7,  2,  5,  4,  5,  6,  5,  6,  4,  3,  4,  5,  6,  4,  7,  5,  3,
        6,  7,  3,  7,  5,  5,  7,  6,  4,  4,  6,  6,  8,  5,  7,  4,  4,
        5,  8,  6,  6,  2,  5,  6,  4,  4,  5,  7,  7,  5,  5,  7,  5,  4,
        5,  6,  4,  2,  6,  2,  4,  6,  7,  2,  2,  3,  1,  5,  8,  7,  3,
        3,  4,  7,  3,  7,  4,  7,  3,  3,  4,  6,  5,  4,  7,  4,  4,  3,
        5,  5,  5,  5,  5,  8,  2,  6,  4,  8,  6,  5,  7,  3,  8,  6,  5,
        5,  4,  6,  8,  6,  3,  7,  5,  6,  3,  5,  4,  3,  8,  4,  6,  5,
        4,  6,  6,  2,  3,  5,  4,  5,  6,  4,  5,  4,  5,  7,  5,  4,  4,
        7,  5,  5,  5,  6

### 3. For each of the three samples:  
- Calculate the mean, median, and standard deviation 
- Find the index and the value of the largest element (hint: `np.argmax()`)  
- Find the value of the 75th percentile (hint: `np.percentile()`)  

In [11]:
mean1 = np.mean(array4)
median1 = np.median(array4)
stddev1 = np.std(array4)
m= np.argmax(array4)
perc1 = np.percentile(array4,75)
print(mean1)
print(median1)
print(stddev1)
print(m)
print(array4[m])
print(perc1)

50.27516540985947
49.76126994590274
29.34848031013264
132
99.61105583000854
76.2280867307779


In [12]:
mean2 = np.mean(array5)
median2 = np.median(array5)
stddev2 = np.std(array5)
b= np.argmax(array5)
perc2 = np.percentile(array5,75)
print(mean2)
print(median2)
print(stddev2)
print(b)
print(array4[b])
print(perc2)

-0.001508197708971263
0.02500026558136798
1.0391142335961292
46
51.27465073998261
0.7308324428772329


In [13]:
mean3 = np.mean(array6)
median3 = np.median(array6)
stddev3 = np.std(array6)
k= np.argmax(array6)
perc3 = np.percentile(array6,75)
print(mean3)
print(median3)
print(stddev3)
print(k)
print(array4[k])
print(perc3)

4.983
5.0
1.6020958148625195
622
89.73166131548415
6.0


### 4. Sort each of the three samples in increasing order, then combine them together to create a 1,000 by 3 array. (hint: `np.sort()` and `np.stack()`). Now, check the shape of the array.

In [16]:
sorted1 = np.sort(array4)
sorted2 = np.sort(array5)
sorted3 = np.sort(array6)
combinedsorted = np.stack((sorted1,sorted2,sorted3), axis = 1)
print(combinedsorted)
combinedsorted.shape

[[ 1.1110819  -3.16530018  1.        ]
 [ 1.21782203 -2.72174343  1.        ]
 [ 1.4720694  -2.69920632  1.        ]
 ...
 [99.49993048  2.75123582  9.        ]
 [99.58717034  2.99570563 10.        ]
 [99.61105583  3.09279186 10.        ]]


(1000, 3)

### 5. Replace all negative values with 0. Replace all values that exceed 10 with 10.

In [17]:
array4[array4<0] = 0
array4[array4>10] = 10
array4

array([10.        , 10.        , 10.        , 10.        ,  7.5744664 ,
       10.        , 10.        , 10.        , 10.        ,  5.09739331,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
        2.67029566, 10.        ,  4.34563742, 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        ,  4.29623321,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
        2.61401675, 10.        , 10.        ,  9.49390648, 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        , 10.        , 10.        , 10.        , 10.        ,
       10.        ,  5.42232867, 10.        , 10.        , 10.  

In [18]:
array5[array5<0] = 0
array5[array5>10] = 10
array5

array([3.70541188e-01, 2.01886002e+00, 1.40791876e+00, 9.87073614e-02,
       0.00000000e+00, 0.00000000e+00, 1.20346232e+00, 8.29031736e-01,
       0.00000000e+00, 0.00000000e+00, 9.03754770e-01, 0.00000000e+00,
       0.00000000e+00, 6.84189239e-01, 1.75220833e+00, 1.37447141e+00,
       0.00000000e+00, 3.55621426e-01, 8.52719604e-01, 0.00000000e+00,
       0.00000000e+00, 2.96754495e-01, 0.00000000e+00, 0.00000000e+00,
       2.53821932e+00, 0.00000000e+00, 7.72825896e-01, 0.00000000e+00,
       1.22477008e+00, 0.00000000e+00, 1.51956488e-01, 4.94906233e-01,
       0.00000000e+00, 4.61774261e-01, 3.60131403e-01, 1.58549165e+00,
       0.00000000e+00, 2.30039088e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.32487775e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.09279186e+00, 1.45142268e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.07230308e-02,
       0.00000000e+00, 7.06652073e-01, 1.26993492e+00, 3.30396731e-01,
      

In [19]:
array6[array6<0] = 0
array6[array6>10] = 10
array6

array([ 4,  6,  5,  4,  5,  8,  6,  6,  6,  6,  5,  5,  6,  4,  8,  4,  7,
        5,  7,  4,  7,  8,  4,  8,  6,  1,  6,  6,  5,  7,  3,  6,  5,  5,
        4,  5,  5,  6,  7,  7,  5,  6,  7,  7,  7,  6,  4,  3,  5,  5,  6,
        6,  5,  6,  5,  6,  7,  7,  2,  6,  5,  1,  5,  6,  4,  6,  7,  5,
        6,  6,  9,  4,  3,  5,  6,  3,  3,  5,  6,  8,  5,  5,  7,  5,  4,
        7,  2,  5,  4,  5,  6,  5,  6,  4,  3,  4,  5,  6,  4,  7,  5,  3,
        6,  7,  3,  7,  5,  5,  7,  6,  4,  4,  6,  6,  8,  5,  7,  4,  4,
        5,  8,  6,  6,  2,  5,  6,  4,  4,  5,  7,  7,  5,  5,  7,  5,  4,
        5,  6,  4,  2,  6,  2,  4,  6,  7,  2,  2,  3,  1,  5,  8,  7,  3,
        3,  4,  7,  3,  7,  4,  7,  3,  3,  4,  6,  5,  4,  7,  4,  4,  3,
        5,  5,  5,  5,  5,  8,  2,  6,  4,  8,  6,  5,  7,  3,  8,  6,  5,
        5,  4,  6,  8,  6,  3,  7,  5,  6,  3,  5,  4,  3,  8,  4,  6,  5,
        4,  6,  6,  2,  3,  5,  4,  5,  6,  4,  5,  4,  5,  7,  5,  4,  4,
        7,  5,  5,  5,  6

### 6. Subtract 5 from all values that exceed 5. (hint: `np.where()`)

In [20]:
np.where(array4 > 5, array4 - 5, array4)

array([5.        , 5.        , 5.        , 5.        , 2.5744664 ,
       5.        , 5.        , 5.        , 5.        , 0.09739331,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       2.67029566, 5.        , 4.34563742, 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 4.29623321,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       2.61401675, 5.        , 5.        , 4.49390648, 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.        ,
       5.        , 0.42232867, 5.        , 5.        , 5.        ,
       5.        , 5.        , 5.        , 5.        , 5.     

In [21]:
np.where(array5 > 5, array5 - 5, array5)

array([3.70541188e-01, 2.01886002e+00, 1.40791876e+00, 9.87073614e-02,
       0.00000000e+00, 0.00000000e+00, 1.20346232e+00, 8.29031736e-01,
       0.00000000e+00, 0.00000000e+00, 9.03754770e-01, 0.00000000e+00,
       0.00000000e+00, 6.84189239e-01, 1.75220833e+00, 1.37447141e+00,
       0.00000000e+00, 3.55621426e-01, 8.52719604e-01, 0.00000000e+00,
       0.00000000e+00, 2.96754495e-01, 0.00000000e+00, 0.00000000e+00,
       2.53821932e+00, 0.00000000e+00, 7.72825896e-01, 0.00000000e+00,
       1.22477008e+00, 0.00000000e+00, 1.51956488e-01, 4.94906233e-01,
       0.00000000e+00, 4.61774261e-01, 3.60131403e-01, 1.58549165e+00,
       0.00000000e+00, 2.30039088e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.32487775e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.09279186e+00, 1.45142268e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.07230308e-02,
       0.00000000e+00, 7.06652073e-01, 1.26993492e+00, 3.30396731e-01,
      

In [22]:
np.where(array6 > 5, array6 - 5, array6)

array([4, 1, 5, 4, 5, 3, 1, 1, 1, 1, 5, 5, 1, 4, 3, 4, 2, 5, 2, 4, 2, 3,
       4, 3, 1, 1, 1, 1, 5, 2, 3, 1, 5, 5, 4, 5, 5, 1, 2, 2, 5, 1, 2, 2,
       2, 1, 4, 3, 5, 5, 1, 1, 5, 1, 5, 1, 2, 2, 2, 1, 5, 1, 5, 1, 4, 1,
       2, 5, 1, 1, 4, 4, 3, 5, 1, 3, 3, 5, 1, 3, 5, 5, 2, 5, 4, 2, 2, 5,
       4, 5, 1, 5, 1, 4, 3, 4, 5, 1, 4, 2, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1,
       4, 4, 1, 1, 3, 5, 2, 4, 4, 5, 3, 1, 1, 2, 5, 1, 4, 4, 5, 2, 2, 5,
       5, 2, 5, 4, 5, 1, 4, 2, 1, 2, 4, 1, 2, 2, 2, 3, 1, 5, 3, 2, 3, 3,
       4, 2, 3, 2, 4, 2, 3, 3, 4, 1, 5, 4, 2, 4, 4, 3, 5, 5, 5, 5, 5, 3,
       2, 1, 4, 3, 1, 5, 2, 3, 3, 1, 5, 5, 4, 1, 3, 1, 3, 2, 5, 1, 3, 5,
       4, 3, 3, 4, 1, 5, 4, 1, 1, 2, 3, 5, 4, 5, 1, 4, 5, 4, 5, 2, 5, 4,
       4, 2, 5, 5, 5, 1, 4, 3, 2, 5, 5, 3, 3, 3, 3, 5, 2, 3, 1, 5, 2, 4,
       4, 5, 4, 2, 3, 2, 3, 2, 4, 5, 3, 5, 2, 5, 4, 2, 1, 4, 2, 4, 5, 1,
       1, 3, 4, 1, 5, 3, 4, 3, 4, 4, 5, 3, 2, 4, 2, 3, 1, 5, 5, 2, 3, 5,
       5, 1, 3, 3, 4, 1, 1, 4, 1, 2, 5, 2, 5, 2, 5,

### 7. Produce a fourth column that is the sum of the first two columns.  (hint: `np.hstack()`). Now check the new shape of the array.

In [25]:
sum_column = combinedsorted[:, 0] + combinedsorted[:, 1]
sum_column = sum_column.reshape(-1, 1)
new_array = np.hstack((combinedsorted, sum_column))
print(new_array.shape)

(1000, 4)


### 8. Use broadcasting to add 1 to each element of the first column, 2 to each element of the second column, 3 to each element of the third column, and 4 to each element of the fourth column.

In [27]:
add_values = np.array([1, 2, 3, 4])
new_array = new_array + add_values
print(new_array)

[[  3.1110819    0.83469982   7.           5.94578172]
 [  3.21782203   1.27825657   7.           6.4960786 ]
 [  3.4720694    1.30079368   7.           6.77286308]
 ...
 [101.49993048   6.75123582  15.         110.25116629]
 [101.58717034   6.99570563  16.         110.58287597]
 [101.61105583   7.09279186  16.         110.70384769]]


### 9. Matrix multiply this 1000x4 array by a 4x1 array of ones. How many unique values are in the resulting product?  (hint: `np.unique()`)

In [29]:
ones_array = np.ones((4, 1))
product = new_array @ ones_array
unique_values = np.unique(product)
print(len(unique_values))

1000


# Thank You